### ISSUE TITLE
Console error: inventory close event

### ISSUE THREAD

**Issue by MillionthOdin16** [SirBlobman/ShulkerPackX#3]
For the last couple weeks I've been getting this error in console when players interact with their shulkers. As far as I can tell, it's not any breaking issue, but I do wonder if it's doing something troublesome.

Current: git-Purpur-1776 (MC: 1.19.2)*
ShulkerPackX version 1.4.1
BlueSlimeCore version 2.5.5.212
ProtocolLib version 5.0.0-SNAPSHOT-b600
 
```
[01:13:20 ERROR]: Could not pass event InventoryCloseEvent to ShulkerPackX v1.4.1
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem cannot be cast to class org.bukkit.inventory.meta.BlockStateMeta (org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem and org.bukkit.inventory.meta.BlockStateMeta are in unnamed module of loader java.net.URLClassLoader @c2e1f26)
        at com.github.sirblobman.shulker.menu.ShulkerBoxMenu.setContents(ShulkerBoxMenu.java:162) ~[ShulkerPackX-1.4.1.jar:?]
        at com.github.sirblobman.shulker.menu.ShulkerBoxMenu.onValidClose(ShulkerBoxMenu.java:58) ~[ShulkerPackX-1.4.1.jar:?]
        at com.github.sirblobman.api.menu.AdvancedAbstractMenu.onCustomClose(AdvancedAbstractMenu.java:47) ~[BlueSlimeCore.jar:?]
        at com.github.sirblobman.api.menu.AdvancedAbstractMenu.onClose(AdvancedAbstractMenu.java:64) ~[BlueSlimeCore.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2249.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1776]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1553) ~[purpur-1.19.2.jar:git-Purpur-1776]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3166) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1367) ~[purpur-1.19.2.jar:git-Purpur-1776]
        at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1550) ~[?:?]
        at net.minecraft.world.level.block.ShulkerBoxBlock.use(ShulkerBoxBlock.java:88) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:1033) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:571) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2050) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1776]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1388) ~[purpur-1.19.2.jar:git-Purpur-1776]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1776]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1365) ~[purpur-1.19.2.jar:git-Purpur-1776]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[purpur-1.19.2.jar:git-Purpur-1776]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[purpur-1.19.2.jar:git-Purpur-1776]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1224) ~[purpur-1.19.2.jar:git-Purpur-1776]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1776]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        ```

**Comment by SirBlobman** [comment]
> `org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem and org.bukkit.inventory.meta.BlockStateMeta are in unnamed module of loader java.net.URLClassLoader @c2e1f26`

Looks like an issue with your server, have you been using `/reload` or a plugin manager?

**Comment by MillionthOdin16** [comment]
I have a plugin manager but not reloading anything for shulker or slime. I have lots of custom recipes though.

**Comment by SirBlobman** [comment]
> I have a plugin manager but not reloading anything for shulker or slime. I have lots of custom recipes though.

Please try removing the plugin manager and fully restarting the server.

**Comment by SirBlobman** [comment]
@MillionthOdin16 I haven't heard from you in a while, if this issue is still occurring please reopen it.
